Repository Learnathon-By-Geeky-Solutions/earendel, pull requests merged in 2025-04, with the labels that each got.

#87 Feature/cd
  .github/workflows/main.yml
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Test/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  sonar-project.properties
Labels: enhancement

#88 Development
  .github/workflows/main.yml
  backend/Api/Framework/Core/Identity/Users/Abstractions/IUserService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/GetAdminsEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/GetInterviewerDetailEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/GetInterviewersEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Framework/Infrastructure/Messaging/BaseConsumer.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/EvaluatorModule.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Messaging/InterviewerFormConsumer.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Get/v1/SeniorityResponse.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Create/v1/CreateSeniorityLevelJunctionCommand.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Create/v1/CreateSeniorityLevelJunctionCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Create/v1/CreateSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Create/v1/CreateSeniorityLevelJunctionResponse.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Get/v1/GetSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Get/v1/SeniorityLevelJunctionResponse.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionCommand.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionResponse.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommand.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillSpec.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/SkillResponse.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillsHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommand.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Get/v1/SubSkillResponse.cs
  backend/Api/Module/Experties/Experties.Domain/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Domain/Skill.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSeniorityLevelJunctionEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/Configurations/SeniorityLevelJunctionConfigurations.cs
  backend/Api/Module/Experties/Experties.Test/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Services/ZoomService.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/HrJobListConsumer.cs
  sonar-project.properties
Labels: enhancement, issue fix

#91 Feature/GitHub authentication
  backend/Api/Framework/Core/Identity/Tokens/Features/Generate/TokenGenerationCommand.cs
  backend/Api/Framework/Core/Identity/Users/Abstractions/IExternalApiClient.cs
  backend/Api/Framework/Core/Identity/Users/Abstractions/IUserService.cs
  backend/Api/Framework/Core/Identity/Users/Features/GithubLogin/GithubRequestCommand.cs
  backend/Api/Framework/Infrastructure/Identity/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Tokens/TokenService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/GithubLoginUserEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/AuthProviders.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
Labels: enhancement

#92 Development
  backend/Api/Framework/Core/Identity/Tokens/Features/Generate/TokenGenerationCommand.cs
  backend/Api/Framework/Core/Identity/Users/Abstractions/IExternalApiClient.cs
  backend/Api/Framework/Core/Identity/Users/Abstractions/IUserService.cs
  backend/Api/Framework/Core/Identity/Users/Features/GithubLogin/GithubRequestCommand.cs
  backend/Api/Framework/Infrastructure/Identity/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Tokens/TokenService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/GithubLoginUserEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/AuthProviders.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
Labels: enhancement, issue fix

#93 Merge User Service to development - Fixed api authentication problem.
  .github/workflows/main.yml
  backend/Api/Module/Candidate/Candidate.Application/CandidateProfile/Update/v1/UpdateCandidateProfileHandler.cs
  backend/Api/Module/Candidate/Candidate.Application/CandidateProfile/Update/v1/UpdateCandidateProfileResponse.cs
  backend/Api/Module/Candidate/Candidate.Domain/Extention/CommonExtension.cs
  backend/Api/Module/Candidate/Candidate.Test/CandidateProfile.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Update/v1/UpdateInterviewerApplicationHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Update/v1/UpdateInterviewerAvailabilityHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Update/v1/UpdateInterviewerEntryFormHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Domain/Extensions/CommonExtension.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/DeleteInterviewerAvailabilityEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/GetInterviewerAvailabilityEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/SearchInterviewerAvailabilitiesEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/UpdateInterviewerAvailabilityEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Messaging/InterviewerFormConsumer.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Persistence/EvaluatorRepository.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerApplicationHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerAvailabilityHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerEntryFormHandlerTests.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Update/v1/UpdateRubricCommand.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Update/v1/UpdateSeniorityCommand.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Get/v1/GetSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Get/v1/GetSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Domain/Rubric.cs
  backend/Api/Module/Experties/Experties.Domain/Seniority.cs
  backend/Api/Module/Experties/Experties.Domain/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Domain/Skill.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Seniority.cs
  backend/Api/Module/Experties/Experties.Test/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Experties/Experties.Test/SubSkill.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Services/ZoomService.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Aspire/Aspire.sln
Labels: enhancement, issue fix

#94 Fix unauthorized authentication problem in Interviewer Dashboard
  .github/workflows/main.yml
  backend/Api/Module/Candidate/Candidate.Application/CandidateProfile/Update/v1/UpdateCandidateProfileHandler.cs
  backend/Api/Module/Candidate/Candidate.Application/CandidateProfile/Update/v1/UpdateCandidateProfileResponse.cs
  backend/Api/Module/Candidate/Candidate.Domain/Extention/CommonExtension.cs
  backend/Api/Module/Candidate/Candidate.Test/CandidateProfile.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Update/v1/UpdateInterviewerApplicationHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Update/v1/UpdateInterviewerAvailabilityHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Update/v1/UpdateInterviewerEntryFormHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Domain/Extensions/CommonExtension.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/DeleteInterviewerAvailabilityEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/GetInterviewerAvailabilityEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/SearchInterviewerAvailabilitiesEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Endpoints/v1/UpdateInterviewerAvailabilityEndpoint.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Messaging/InterviewerFormConsumer.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Persistence/EvaluatorRepository.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerApplicationHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerAvailabilityHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerEntryFormHandlerTests.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Update/v1/UpdateRubricCommand.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Update/v1/UpdateSeniorityCommand.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Get/v1/GetSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Get/v1/GetSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Domain/Rubric.cs
  backend/Api/Module/Experties/Experties.Domain/Seniority.cs
  backend/Api/Module/Experties/Experties.Domain/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Domain/Skill.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Seniority.cs
  backend/Api/Module/Experties/Experties.Test/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Experties/Experties.Test/SubSkill.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Services/ZoomService.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Aspire/Aspire.sln
Labels: enhancement, issue fix

#97 Candidate View Logic Merged To Development
  .gitignore
  backend/Api/Module/CandidateLogic/CandidateLogic.csproj
  backend/Api/Module/CandidateLogic/CandidateLogicMetadata.cs
  backend/Api/Module/CandidateLogic/CandidateLogicModule.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewEndpoint.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewFilters.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewService.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewEndpoint.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewFilters.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewService.cs
  backend/Api/Module/Jobs/Jobs.Domain/JobApplication.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Persistence/JobRepository.cs
  backend/Api/Server/Extensions.cs
  backend/Api/Server/Server.csproj
  backend/Aspire/Aspire.sln
Labels: enhancement, issue fix

#110 Merge development to main - HR Module And Quick Fix For Quiz Module
  backend/Api/Module/CandidateLogic/CandidateLogicModule.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewDTO.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewService.cs
  backend/Api/Module/CandidateLogic/Quiz/GetRandomQuizQuestionQueryHandler.cs
  backend/Api/Module/CandidateLogic/Quiz/SubmitAnswerCommandHandler.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommand.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommandHandler.cs
  backend/Api/Module/HRView/HRFunc/CreateJobEndpoint.cs
  backend/Api/Module/HRView/HRFunc/GetAllJobApplicationsEndpoint.cs
  backend/Api/Module/HRView/HRFunc/GetAllJobApplicationsQuery.cs
  backend/Api/Module/HRView/HRFunc/GetAllJobApplicationsQueryHandler.cs
  backend/Api/Module/HRView/HRFunc/JobApplicationDto.cs
  backend/Api/Module/HRView/HRView.csproj
  backend/Api/Module/HRView/HRViewMetadata.cs
  backend/Api/Module/HRView/HRViewModule.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Create/v1/CreateJobCommand.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Create/v1/CreateJobCommandValidator.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Create/v1/CreateJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Get/v1/GetJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Get/v1/JobResponse.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Update/v1/UpdateJobCommand.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Update/v1/UpdateJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Domain/JobApplication.cs
  backend/Api/Module/Jobs/Jobs.Domain/Jobs.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Persistence/JobDbInitializer.cs
  backend/Api/Module/Quizzes/Quizzes.Domain/QuizAttemptAnswer.cs
  backend/Api/Server/Extensions.cs
  backend/Api/Server/Server.csproj
  backend/Aspire/Aspire.sln
  backend/Dockerfile
Labels: enhancement

#119 Fix(Candidate Logic): Endpoint Added To Carter
  backend/Api/Module/CandidateLogic/CandidateLogicModule.cs
Labels: bug

#120 Fix(Candidate Logic): Endpoint Added To Carter and Add it to the Main from development
  backend/Api/Module/CandidateLogic/CandidateLogicModule.cs
Labels: bug

#102 Feature/ssl commerz
  backend/Api/Framework/Core/Identity/Users/Abstractions/IExternalApiClient.cs
  backend/Api/Framework/Core/Identity/Users/Abstractions/IUserService.cs
  backend/Api/Framework/Core/Mail/IMailService.cs
  backend/Api/Framework/Core/Mail/MailRequest.cs
  backend/Api/Framework/Infrastructure/Auth/CurrentUserMiddleware.cs
  backend/Api/Framework/Infrastructure/Auth/DefaultTenantMiddleware.cs
  backend/Api/Framework/Infrastructure/Auth/Jwt/Extensions.cs
  backend/Api/Framework/Infrastructure/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Tokens/TokenService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/ConfirmUserEmailEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/Extensions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.Password.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/TMUser.cs
  backend/Api/Framework/Infrastructure/Mail/Extensions.cs
  backend/Api/Framework/Infrastructure/Mail/SmtpMailService.cs
  backend/Api/Framework/Infrastructure/Tenant/Extensions.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Get/v1/GetRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricsCommand.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillsHandler.cs
  backend/Api/Module/Experties/Experties.Domain/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
Labels: enhancement, issue fix

#137 Fix swagger documentation changes
  .gitignore
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewEndpoint.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewEndpoint.cs
  backend/Api/Module/InterviewerView/InterviewerView/ApproveInterviewerEndpoint.cs
  backend/Api/Module/InterviewerView/InterviewerView/InterviewStatsEndpoints.cs
  backend/Api/Module/InterviewerView/InterviewerView/RequestInterviewerEndpoint.cs
  backend/Api/Server/CVEndpoint.cs
Labels: documentation

#139 Merge frontend-integration/candidate-dashboard to the frontend branch
  src/app/app.routes.ts
  src/app/candidate-dashboard/candidate-dashboard.module.ts
  src/app/candidate-dashboard/job-details/job-details.component.ts
  src/app/candidate-dashboard/job-posts/job-posts.component.ts
  src/app/candidate-dashboard/quiz-interface/quiz-interface.component.ts
  src/app/candidate-dashboard/quiz-list/quiz-list.component.ts
  src/app/candidate-dashboard/quiz-results/quiz-results.component.ts
  src/app/candidate-dashboard/quiz-start/quiz-start.component.ts
  src/app/candidate-dashboard/services/candidate.service.ts
  src/app/candidate-dashboard/services/job.service.ts
  src/app/candidate-dashboard/services/quiz.service.ts
  src/app/endpoints/endpoint.ts
  src/app/shared/services/job.service.ts
  src/favicon.ico
Labels: enhancement

#145 Frontend integration/admin dashboard
  package-lock.json
  package.json
  src/app/Language.ts
  src/app/admin-dashboard/services/verification.service.spec.ts
  src/app/admin-dashboard/services/verification.service.ts
  src/app/admin-dashboard/verification/verification.component.ts
  src/app/app.routes.ts
  src/app/candidate-dashboard/interviewer-registration/interviewer-registration.component.ts
  src/app/code.service.spec.ts
  src/app/code.service.ts
  src/app/code/code.component.css
  src/app/code/code.component.html
  src/app/code/code.component.spec.ts
  src/app/code/code.component.ts
  src/app/core/service/api.service.ts
  src/app/endpoints/endpoint.ts
  src/app/shared/services/home.service.ts
  src/app/zoomsdk/zoomsdk.component.css
  src/app/zoomsdk/zoomsdk.component.html
  src/app/zoomsdk/zoomsdk.component.spec.ts
  src/app/zoomsdk/zoomsdk.component.ts
  src/environments/environment.ts
Labels: enhancement

#146 Merge frontend with frontend-candidate dashboard
  package-lock.json
  package.json
  src/app/Language.ts
  src/app/admin-dashboard/services/verification.service.spec.ts
  src/app/admin-dashboard/services/verification.service.ts
  src/app/admin-dashboard/verification/verification.component.ts
  src/app/app.routes.ts
  src/app/candidate-dashboard/interviewer-registration/interviewer-registration.component.ts
  src/app/code.service.spec.ts
  src/app/code.service.ts
  src/app/code/code.component.css
  src/app/code/code.component.html
  src/app/code/code.component.spec.ts
  src/app/code/code.component.ts
  src/app/core/service/api.service.ts
  src/app/endpoints/endpoint.ts
  src/app/hr-dashboard/job-post/customize-interview/customize-interview.component.ts
  src/app/shared/services/home.service.ts
  src/app/zoomsdk/zoomsdk.component.css
  src/app/zoomsdk/zoomsdk.component.html
  src/app/zoomsdk/zoomsdk.component.spec.ts
  src/app/zoomsdk/zoomsdk.component.ts
  src/environments/environment.ts
Labels: issue fix

#147 Feature/refactoring
  backend/Api/Framework/Core/Identity/Users/Abstractions/IExternalApiClient.cs
  backend/Api/Framework/Core/Specifications/SpecificationExtensions.cs
  backend/Api/Framework/Infrastructure/Identity/Persistence/IdentityDbInitializer.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.Permissions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Delete/v1/DeleteRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Get/v1/GetRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Update/v1/UpdateRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Delete/v1/DeleteSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Get/v1/GetSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Search/v1/SearchSenioritySpecs.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Update/v1/UpdateSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Domain/Rubric.cs
  backend/Api/Module/Experties/Experties.Domain/Seniority.cs
  backend/Api/Module/Experties/Experties.Domain/Skill.cs
  backend/Api/Module/Experties/Experties.Domain/SubSkill.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateRubricEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSeniorityEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSkillEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSubSkillEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/ExpertiesDbInitializer.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/ExpertiesRepository.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/JobModule.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/JobPaymentUpdatedConsumer.cs
  backend/Dockerfile
  backend/Shared/Authorization/TMPermissions.cs
Labels: enhancement

#148 Development
  backend/Api/Framework/Core/Identity/Users/Abstractions/IExternalApiClient.cs
  backend/Api/Framework/Core/Specifications/SpecificationExtensions.cs
  backend/Api/Framework/Infrastructure/Identity/Persistence/IdentityDbInitializer.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.Permissions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Delete/v1/DeleteRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Get/v1/GetRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Update/v1/UpdateRubricHandler.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Delete/v1/DeleteSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Get/v1/GetSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Search/v1/SearchSenioritySpecs.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Update/v1/UpdateSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Domain/Rubric.cs
  backend/Api/Module/Experties/Experties.Domain/Seniority.cs
  backend/Api/Module/Experties/Experties.Domain/Skill.cs
  backend/Api/Module/Experties/Experties.Domain/SubSkill.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateRubricEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSeniorityEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSkillEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Endpoints/v1/UpdateSubSkillEndpoint.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/ExpertiesDbInitializer.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/ExpertiesRepository.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommandHandler.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/JobModule.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/JobPaymentUpdatedConsumer.cs
  backend/Dockerfile
  backend/Shared/Authorization/TMPermissions.cs
Labels: bug

#150 refactor: fix sonarcloud issues
  backend/Api/Framework/Core/Paging/PaginationFilter.cs
  backend/Api/Framework/Core/Specifications/SpecificationBuilderExtensions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UsersConsumer.cs
  backend/Api/Framework/Infrastructure/Jobs/Extensions.cs
  backend/Api/Framework/Infrastructure/Jobs/HangfireCustomBasicAuthenticationFilter.cs
  backend/Api/Framework/Infrastructure/Messaging/BaseConsumer.cs
  backend/Api/Framework/Infrastructure/Messaging/RabbitMQMessageBus.cs
  backend/Api/Framework/Infrastructure/Messaging/RabbitMqConsumerBase.cs
  backend/Api/Module/Candidate/Candidate.Application/CandidateProfile/Search/v1/SearchCandidateProfileSpecs.cs
  backend/Api/Module/Candidate/Candidate.Test/CandidateProfile.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewEndpoint.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewService.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewService.cs
  backend/Api/Module/CandidateLogic/Quiz/GetUserQuizAttemptsQueryHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Search/v1/SearchInterviewerEntryFormSpecs.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Search/v1/SearchInterviewerEntryFormsCommand.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Messaging/InterviewerFormConsumer.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerApplicationHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerAvailabilityHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerEntryFormHandlerTests.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommand.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Seniority.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Experties/Experties.Test/SubSkill.cs
Labels: bug

#151 Sonarcloud issues fix
  backend/Api/Framework/Core/Paging/PaginationFilter.cs
  backend/Api/Framework/Core/Specifications/SpecificationBuilderExtensions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UsersConsumer.cs
  backend/Api/Framework/Infrastructure/Jobs/Extensions.cs
  backend/Api/Framework/Infrastructure/Jobs/HangfireCustomBasicAuthenticationFilter.cs
  backend/Api/Framework/Infrastructure/Messaging/BaseConsumer.cs
  backend/Api/Framework/Infrastructure/Messaging/RabbitMQMessageBus.cs
  backend/Api/Framework/Infrastructure/Messaging/RabbitMqConsumerBase.cs
  backend/Api/Module/Candidate/Candidate.Application/CandidateProfile/Search/v1/SearchCandidateProfileSpecs.cs
  backend/Api/Module/Candidate/Candidate.Test/CandidateProfile.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewEndpoint.cs
  backend/Api/Module/CandidateLogic/JobApplicationView/JobApplicationViewService.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewService.cs
  backend/Api/Module/CandidateLogic/Quiz/GetUserQuizAttemptsQueryHandler.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Search/v1/SearchInterviewerEntryFormSpecs.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Search/v1/SearchInterviewerEntryFormsCommand.cs
  backend/Api/Module/Evaluator/Evaluator.Infrastructure/Messaging/InterviewerFormConsumer.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerApplicationHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerAvailabilityHandlerTests.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerEntryFormHandlerTests.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Update/v1/UpdateSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommand.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Seniority.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Experties/Experties.Test/SubSkill.cs
Labels: bug

#154 fix: fix sonarcloud issues
  backend/Api/Framework/Infrastructure/Identity/Persistence/IdentityDbInitializer.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.Permissions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UsersConsumer.cs
  backend/Api/Framework/Infrastructure/Jobs/HangfireCustomBasicAuthenticationFilter.cs
  backend/Api/Framework/Infrastructure/Messaging/BaseConsumer.cs
  backend/Api/Framework/Infrastructure/Messaging/RabbitMqConsumerBase.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerEntryFormHandlerTests.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Get/v1/GetSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Get/v1/GetSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommand.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Messaging/SkillsCreatedConsumer.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/ExpertiesDbInitializer.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Seniority.cs
  backend/Api/Module/Experties/Experties.Test/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Experties/Experties.Test/SubSkill.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommandHandler.cs
  backend/Api/Module/HRView/HRFunc/CreateJobEndpoint.cs
  backend/Api/Module/HRView/HRFunc/GetAllJobApplicationsQueryHandler.cs
  backend/Api/Module/HRView/HRFunc/GetMyJobsQueryHandler.cs
  backend/Api/Module/HRView/HRFunc/JobDto.cs
  backend/Api/Module/InterviewerView/InterviewerView/ApproveInterviewerHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/RejectInterviewerHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/RequestInterviewerHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/UpcommingInterviews.cs
  backend/Api/Module/InterviewerView/InterviewerViewModule.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewSignatureHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Get/v1/GetInterviewByInterviewerHandler.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Services/ZoomService.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Api/Module/Interviews/Interviews.Test/InterviewFeedback.cs
  backend/Api/Module/Interviews/Interviews.Test/InterviewQuestion.cs
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Delete/v1/DeleteJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Delete/v1/DeleteJobRequiredSkillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Delete/v1/DeleteJobRequiredSubskillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Delete/v1/DeleteJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Get/v1/GetJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Search/v1/SearchJobSpecs.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/HrJobListConsumer.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/InterviewApplicationConsumer.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Persistence/NotificationsRepository.cs
  backend/Api/Module/Notifications/Notifications.Test/Notification.cs
  backend/Api/Module/Quizzes/Quizzes.Application/QuizQuestions/Search/v1/SearchQuizQuestionSpecs.cs
  backend/Api/Module/Quizzes/Quizzes.Test/QuizAttempt.cs
  backend/Api/Module/Quizzes/Quizzes.Test/QuizAttemptAnswer.cs
  backend/Api/Module/Quizzes/Quizzes.Test/QuizQuesion.cs
  backend/Api/Server/CVEndpoint.cs
  backend/Shared/Authorization/TMPermissions.cs
Labels: issue fix

#155 Fix Sonarcloud Issues
  backend/Api/Framework/Infrastructure/Identity/Persistence/IdentityDbInitializer.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.Permissions.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UsersConsumer.cs
  backend/Api/Framework/Infrastructure/Jobs/HangfireCustomBasicAuthenticationFilter.cs
  backend/Api/Framework/Infrastructure/Messaging/BaseConsumer.cs
  backend/Api/Framework/Infrastructure/Messaging/RabbitMqConsumerBase.cs
  backend/Api/Module/Evaluator/Evaluator.Test/InterviewerEntryFormHandlerTests.cs
  backend/Api/Module/Experties/Experties.Application/Seniorities/Get/v1/GetSeniorityHandler.cs
  backend/Api/Module/Experties/Experties.Application/SeniorityLevelJunctions/Get/v1/GetSeniorityLevelJunctionHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillCommand.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Messaging/SkillsCreatedConsumer.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Persistence/ExpertiesDbInitializer.cs
  backend/Api/Module/Experties/Experties.Test/Rubric.cs
  backend/Api/Module/Experties/Experties.Test/Seniority.cs
  backend/Api/Module/Experties/Experties.Test/SeniorityLevelJunction.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/Experties/Experties.Test/SubSkill.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommandHandler.cs
  backend/Api/Module/HRView/HRFunc/CreateJobEndpoint.cs
  backend/Api/Module/HRView/HRFunc/GetAllJobApplicationsQueryHandler.cs
  backend/Api/Module/HRView/HRFunc/GetMyJobsQueryHandler.cs
  backend/Api/Module/HRView/HRFunc/JobDto.cs
  backend/Api/Module/InterviewerView/InterviewerView/ApproveInterviewerHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/RejectInterviewerHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/RequestInterviewerHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/UpcommingInterviews.cs
  backend/Api/Module/InterviewerView/InterviewerViewModule.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewSignatureHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Get/v1/GetInterviewByInterviewerHandler.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Services/ZoomService.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Api/Module/Interviews/Interviews.Test/InterviewFeedback.cs
  backend/Api/Module/Interviews/Interviews.Test/InterviewQuestion.cs
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Delete/v1/DeleteJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Delete/v1/DeleteJobRequiredSkillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Delete/v1/DeleteJobRequiredSubskillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Delete/v1/DeleteJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Get/v1/GetJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Search/v1/SearchJobSpecs.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/HrJobListConsumer.cs
  backend/Api/Module/Jobs/Jobs.Infrastructure/Messaging/InterviewApplicationConsumer.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Persistence/NotificationsRepository.cs
  backend/Api/Module/Notifications/Notifications.Test/Notification.cs
  backend/Api/Module/Quizzes/Quizzes.Application/QuizQuestions/Search/v1/SearchQuizQuestionSpecs.cs
  backend/Api/Module/Quizzes/Quizzes.Test/QuizAttempt.cs
  backend/Api/Module/Quizzes/Quizzes.Test/QuizAttemptAnswer.cs
  backend/Api/Module/Quizzes/Quizzes.Test/QuizQuesion.cs
  backend/Api/Server/CVEndpoint.cs
  backend/Shared/Authorization/TMPermissions.cs
Labels: issue fix

#158 Frontend integration/admin dashboard
  src/app/core/interceptors/http.interceptor.ts
  src/app/endpoints/endpoint.ts
  src/app/shared/services/signalr/notificationhub.service.ts
Labels: documentation

#163 refactor: add candidateId, jobId field on interview module
  Migrations/PGSql/obj/.EntityFrameworkCore.targets
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Search/v1/SearchInterviewSpecs.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Search/v1/SearchInterviewsCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Domain/Interview.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Persistence/InterviewsDbInitializer.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Api/Module/Notifications/Notifications.Application/Notifications/Search/v1/SearchNotificationSpecs.cs
Labels: documentation

#164 fix: Add candidateId, jobId on InterviewResponse
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Get/v1/GetInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Get/v1/InterviewResponse.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
Labels: issue fix

#165 fix: fix few things
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Delete/v1/DeleteSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Delete/v1/DeleteSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Get/v1/GetSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Update/v1/UpdateSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
Labels: issue fix

#166 Chore/code enhancement
  backend/Api/Framework/Infrastructure/Jobs/TMJobFilter.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommandHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/CreateInterviewFeedbackRequest.cs
  backend/Api/Module/InterviewerView/InterviewerView/InterviewFeedbackDto.cs
  backend/Api/Module/InterviewerView/InterviewerView/InterviewStatsEndpoints.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Get/v1/GetInterviewFeedbackHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Get/v1/InterviewFeedbackResponse.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Search/v1/SearchInterviewFeedbackSpecs.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Search/v1/SearchInterviewFeedbacksCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Domain/InterviewFeedback.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Persistence/Configurations/InterviewFeedbackConfiguration.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Api/Module/Interviews/Interviews.Test/InterviewFeedback.cs
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Create/v1/CreateJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs.Application.csproj
  backend/Api/Module/Notifications/Notifications.Infrastructure/Messaging/NotificationConsumer.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Notifications.Infrastructure.csproj
Labels: documentation

#167 Development
  Migrations/PGSql/obj/.EntityFrameworkCore.targets
  backend/Api/Framework/Infrastructure/Jobs/TMJobFilter.cs
  backend/Api/Framework/Infrastructure/SignalR/NotificationHub.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Create/v1/CreateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Delete/v1/DeleteSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Get/v1/GetSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Search/v1/SearchSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillCommandValidator.cs
  backend/Api/Module/Experties/Experties.Application/Skills/Update/v1/UpdateSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Delete/v1/DeleteSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Get/v1/GetSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Search/v1/SearchSubSkillSpecs.cs
  backend/Api/Module/Experties/Experties.Application/SubSkills/Update/v1/UpdateSubSkillHandler.cs
  backend/Api/Module/Experties/Experties.Test/Skill.cs
  backend/Api/Module/HRView/HRFunc/CreateJobCommandHandler.cs
  backend/Api/Module/InterviewerView/InterviewerView/CreateInterviewFeedbackRequest.cs
  backend/Api/Module/InterviewerView/InterviewerView/InterviewFeedbackDto.cs
  backend/Api/Module/InterviewerView/InterviewerView/InterviewStatsEndpoints.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Get/v1/GetInterviewFeedbackHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Get/v1/InterviewFeedbackResponse.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Search/v1/SearchInterviewFeedbackSpecs.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Search/v1/SearchInterviewFeedbacksCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackCommand.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Domain/InterviewFeedback.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Persistence/Configurations/InterviewFeedbackConfiguration.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Api/Module/Interviews/Interviews.Test/InterviewFeedback.cs
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Create/v1/CreateJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs.Application.csproj
  backend/Api/Module/Jobs/Jobs.Test/JobApplicationTests.cs
  backend/Api/Module/Jobs/Jobs.Test/JobRequiredSkillTests.cs
  backend/Api/Module/Jobs/Jobs.Test/JobRequiredSubskillTests.cs
  backend/Api/Module/Jobs/Jobs.Test/Jobs.Test.csproj
  backend/Api/Module/Jobs/Jobs.Test/JobsTests.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Messaging/NotificationConsumer.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Notifications.Infrastructure.csproj
  backend/Api/Module/Notifications/Notifications.Infrastructure/NotificationsModule.cs
  backend/Aspire/Aspire.sln
Labels: documentation

#171 Frontend integration/candidate dashboard
  src/app/candidate-dashboard/job-details/job-details.component.ts
  src/app/candidate-dashboard/job-posts/job-posts.component.ts
  src/app/candidate-dashboard/services/job.service.ts
Labels: documentation

#172 Frontend integration/hr dashboard
  src/app/app.routes.ts
  src/app/endpoints/endpoint.ts
  src/app/hr-dashboard/customize/customize-interview/customize-interview.component.css
  src/app/hr-dashboard/customize/customize-interview/customize-interview.component.html
  src/app/hr-dashboard/customize/customize-interview/customize-interview.component.spec.ts
  src/app/hr-dashboard/customize/customize-interview/customize-interview.component.ts
  src/app/hr-dashboard/customize/customize-panel/customize-panel.component.ts
  src/app/hr-dashboard/customize/rubrics-config/rubrics-config.component.css
  src/app/hr-dashboard/customize/rubrics-config/rubrics-config.component.html
  src/app/hr-dashboard/customize/rubrics-config/rubrics-config.component.spec.ts
  src/app/hr-dashboard/customize/rubrics-config/rubrics-config.component.ts
  src/app/hr-dashboard/interview-request/interview-request.component.html
  src/app/hr-dashboard/interview-request/interview-request.component.ts
  src/app/hr-dashboard/job-post/customize-interview/customize-interview.component.ts
  src/app/hr-dashboard/job-post/profile-selection/profile-selection.component.ts
  src/app/hr-dashboard/job-post/seniority-selection/seniority-selection.component.html
  src/app/hr-dashboard/job-post/seniority-selection/seniority-selection.component.ts
  src/app/hr-dashboard/job-post/technology-selection/technology-selection.component.html
  src/app/hr-dashboard/job-post/technology-selection/technology-selection.component.ts
  src/app/hr-dashboard/jobs/jobs.component.ts
  src/app/hr-dashboard/seniority-select/seniority-select.component.ts
  src/app/hr-dashboard/services/job-posting.service.ts
  src/app/hr-dashboard/services/job.service.spec.ts
  src/app/hr-dashboard/services/job.service.ts
Labels: documentation

#176 chore(ci): split main.yml into deploy.yml and ci-cd.yml
  .github/workflows/build-and-publish.yml
  .github/workflows/deploy.yml
Labels: issue fix

#178 Development
  .github/workflows/build-and-publish.yml
  .github/workflows/deploy.yml
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Delete/v1/DeleteJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Get/v1/GetJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Delete/v1/DeleteJobRequiredSkillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Get/v1/GetJobRequiredSkillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Update/v1/UpdateJobRequiredSkillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Delete/v1/DeleteJobRequiredSubskillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Get/v1/GetJobRequiredSubskillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Update/v1/UpdateJobRequiredSubskillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Delete/v1/DeleteJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Get/v1/JobResponse.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Update/v1/UpdateJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Domain/Extention/CommonExtension.cs
  backend/Api/Module/Jobs/Jobs.Test/JobApplicationHandlerTests.cs
  backend/Api/Module/Jobs/Jobs.Test/JobHandlerTest.cs
Labels: issue fix

#179 core: split ci/cd into two parts
  .github/workflows/build-and-publish.yml
Labels: issue fix

#180 Fix (HR-Dashboard): endpoint URL formatting and remove unused imports…
  src/app/endpoints/endpoint.ts
  src/app/hr-dashboard/job-post/customize-interview/customize-interview.component.ts
Labels: documentation

#182 (HR-Dashboard): Implemented interview feedback report feature with PD…
  package-lock.json
  package.json
  src/app/app.routes.ts
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.css
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.html
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.spec.ts
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.ts
  src/app/hr-dashboard/jobs/jobs.component.ts
Labels: documentation

#183 refactor: Add interviewsignature permissions
  backend/Shared/Authorization/TMPermissions.cs
  backend/Shared/Authorization/TMResources.cs
Labels: issue fix

#184 fix: fix build errors
  backend/Shared/Authorization/TMPermissions.cs
Labels: issue fix

#185 Frontend integration/report gen
  package-lock.json
  package.json
  src/app/app.routes.ts
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.css
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.html
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.ts
  src/app/zoomsdk/zoomsdk.component.ts
Labels: documentation

#186 fix: fix sonarcloud errors
  backend/Api/Framework/Infrastructure/Identity/Users/Services/UserService.cs
  backend/Api/Framework/Infrastructure/SignalR/NotificationHub.cs
  backend/Api/Module/Experties/Experties.Application/Rubrics/Search/v1/SearchRubricSpecs.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Messaging/SkillsCreatedConsumer.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Create/v1/CreateInterviewFeedbackCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/InterviewFeedbacks/Update/v1/UpdateInterviewFeedbackCommandValidator.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Create/v1/CreateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Application/Interviews/Update/v1/UpdateInterviewHandler.cs
  backend/Api/Module/Interviews/Interviews.Domain/Interview.cs
  backend/Api/Module/Interviews/Interviews.Domain/InterviewDto.cs
  backend/Api/Module/Interviews/Interviews.Domain/InterviewFeedback.cs
  backend/Api/Module/Interviews/Interviews.Infrastructure/Persistence/InterviewsDbInitializer.cs
  backend/Api/Module/Interviews/Interviews.Test/Interview.cs
  backend/Api/Module/Jobs/Jobs.Application/JobApplication/Delete/v1/DeleteJobApplicationHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSkill/Delete/v1/DeleteJobRequiredSkillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/JobRequiredSubskill/Delete/v1/DeleteJobRequiredSubskillHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Delete/v1/DeleteJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Application/Jobs/Update/v1/UpdateJobHandler.cs
  backend/Api/Module/Jobs/Jobs.Domain/JobDetails.cs
  backend/Api/Module/Jobs/Jobs.Domain/Jobs.cs
  backend/Api/Module/Jobs/Jobs.Test/JobDomainTests.cs
  backend/Api/Module/Jobs/Jobs.Test/JobHandlerTest.cs
  backend/Api/Module/Jobs/Jobs.Test/JobsTests.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Messaging/NotificationConsumer.cs
Labels: issue fix

#187 fix: fix build errors
  backend/Api/Framework/Infrastructure/Messaging/RabbitMqConsumerBase.cs
  backend/Api/Module/Experties/Experties.Infrastructure/Messaging/SkillsCreatedConsumer.cs
  backend/Api/Module/Jobs/Jobs.Domain/Jobs.cs
  backend/Api/Module/Notifications/Notifications.Infrastructure/Messaging/NotificationConsumer.cs
Labels: issue fix

#188 fix: increase script time on deployment
  .github/workflows/deploy.yml
Labels: issue fix

#190 update routes file
  src/app/app.routes.ts
Labels: issue fix

#192 chore: add job filtering logic
  .github/workflows/build-and-publish.yml
  .github/workflows/deploy.yml
  backend/Api/Framework/Infrastructure/Identity/Users/Endpoints/SSLCommerzSuccessEndpoint.cs
  backend/Api/Framework/Infrastructure/Identity/Users/Services/ExternalApiClient.cs
  backend/Api/Module/CandidateLogic/JobView/JobViewService.cs
  backend/Api/Module/Experties/Experties.Application/Skills/EventHandlers/SkillCreatedEventHandler.cs
Labels: enhancement

#195 fix: fix available time format
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityCommandValidator.cs
Labels: documentation

#198 fix docker copy issue
  backend/Api/Framework/Infrastructure/Identity/Tokens/TokenService.cs
  backend/Dockerfile
Labels: issue fix

#199 fix: available time issues
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityCommandValidator.cs
  backend/Api/Module/Evaluator/Evaluator.Application/Interviewer/Create/v1/CreateInterviewerAvailabilityHandler.cs
Labels: issue fix

#200 Frontend integration/report gen
  .editorconfig
  src/app/admin-dashboard/notifications/notifications.component.ts
  src/app/candidate-dashboard/candidate-sidebar/candidate-sidebar.component.ts
  src/app/candidate-dashboard/notifications/notifications.component.ts
  src/app/candidate-dashboard/requested-interviews/requested-interviews.component.css
  src/app/candidate-dashboard/requested-interviews/requested-interviews.component.html
  src/app/candidate-dashboard/requested-interviews/requested-interviews.component.ts
  src/app/candidate-dashboard/services/job.service.ts
  src/app/endpoints/endpoint.ts
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.html
  src/app/hr-dashboard/jobs/interview-report/interview-report.component.ts
  src/app/hr-dashboard/notifications/notifications.component.ts
  src/app/interviewer-dashboard/availability/availability.component.html
  src/app/interviewer-dashboard/availability/availability.component.ts
  src/app/interviewer-dashboard/notification/notification.component.html
  src/app/interviewer-dashboard/notifications/notifications.component.ts
Labels: documentation

#202 Frontend integration/report gen
  src/app/admin-dashboard/hr/hr.component.ts
  src/app/admin-dashboard/services/skill.service.ts
  src/app/admin-dashboard/sidebar/sidebar.component.ts
  src/app/candidate-dashboard/candidate-sidebar/candidate-sidebar.component.ts
  src/app/endpoints/endpoint.ts
  src/app/hr-dashboard/sidebar/sidebar.component.ts
  src/app/interviewer-dashboard/sidebar/sidebar.component.ts
  src/app/shared/services/login-signup.service.ts
Labels: documentation

#205 add skill and subskill name on job views
  src/app/candidate-dashboard/job-details/job-details.component.ts
Labels: documentation

#206 fix: give file upload permissions to the cadidate
  backend/Api/Server/CVEndpoint.cs
  backend/Shared/Authorization/TMPermissions.cs
Labels: issue fix
